add_newline = true

format = """
╭──$os$username$hostname[](fg:#ffffff) $directory
│
╰──$git_branch$git_status$git_state$git_metrics$docker_context$kubernetes$terraform$c$cpp$python$rust$nodejs$go$java$php$ruby$haskell$zig$swift$kotlin$dotnet$bun$deno$lua$cmake$package$character
"""

########################################
#####---------- Hardware ----------#####
########################################
right_format = """$memory_usage$battery$cmd_duration$time"""

[os]
disabled = false
style = "bg:#ffffff fg:#000000"
format = "[$symbol]($style)"

[os.symbols]
Macos = "󰀵 "
Linux = "󰻀 "
Windows = "󰍲 "

[username]
show_always = true
style_user = "bg:#ffffff fg:#000000"
style_root = "bg:#ffffff fg:#000000"
format = "[$user]($style)"

[hostname]
ssh_only = false 
style = "bg:#ffffff fg:#000000"
format = "[@$hostname]($style)"

[directory]
style = "fg:#ffffff"
format = "[ 󰉋 ](bg:#ffffff fg:#000000) [ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󱑢 "
"Music" = "󰝚 "
"Pictures" = "󰙏 "
"Developer" = "󟤧 "

[git_branch]
symbol = "󰘬"
style = "fg:#a6adc8"
format = " [ $symbol $branch ](bg:#a6adc8 fg:#000000)"

[git_status]
style = "fg:#ffffff"
format = "[[($all_status$ahead_behind )]($style)]($style)"

[git_metrics]
disabled = false
added_style = "fg:#a6adc8"
deleted_style = "fg:#a6adc8"
format = "[+$added]($added_style)/[-$deleted]($deleted_style) "

#########################################
#####---------- Languages ----------#####
#########################################
[python]
symbol = "󱔎 "
style = "fg:#7f849c"
format = " [ $symbol($virtualenv) ](bg:#7f849c fg:#000000)"

[rust]
symbol = "󱘗 "
style = "fg:#7f849c"
format = " [ $symbol($version) ](bg:#7f849c fg:#000000)"

[nodejs]
symbol = "󰎙 "
style = "fg:#7f849c"
format = " [ $symbol($version) ](bg:#7f849c fg:#000000)"

[cpp]
symbol = " "
style = "fg:#7f849c"
format = " [ $symbol($version) ](bg:#7f849c fg:#000000)"

[c]
symbol = " "
style = "fg:#7f849c"
format = " [ $symbol($version) ](bg:#7f849c fg:#000000)"

[lua]
symbol = "󰢱 "
style = "fg:#7f849c"
format = " [ $symbol($version) ](bg:#7f849c fg:#000000)"

#######################################
#####---------- Modules ----------#####
#######################################
[memory_usage]
disabled = false
threshold = 30
style = "fg:#585b70"
symbol = "󰍛 "
format = "[$symbol${ram} ]($style)"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 20
style = "fg:#ffffff"

[time]
disabled = false
time_format = "%R"
style = "fg:#585b70"
format = "󱑒 $time "

[cmd_duration]
min_time = 500
style = "fg:#585b70"
format = "󱎫 $duration "

#####################################
#####---------- Input ----------#####
#####################################
[character]
success_symbol = " [󰄾 ](fg:#ffffff)"
error_symbol = " [󰅙 ](fg:#ff6666)"
